name: CI/CD Pipeline (Test Mode)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: mydatabase
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U myuser"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start all services with Docker Compose
        run: |
          docker-compose up -d
          sleep 10

      - name: Run tests
        run: |
          docker-compose exec -T fastapi pytest tests/

      - name: Stop services
        run: docker-compose down

  simulate_deploy:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Simulating deployment
        run: echo "Deployment simulation successful! 🚀"
